// Generated by gencpp from file pwm_control/PWMValues.msg
// DO NOT EDIT!


#ifndef PWM_CONTROL_MESSAGE_PWMVALUES_H
#define PWM_CONTROL_MESSAGE_PWMVALUES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pwm_control
{
template <class ContainerAllocator>
struct PWMValues_
{
  typedef PWMValues_<ContainerAllocator> Type;

  PWMValues_()
    : outputs()  {
    }
  PWMValues_(const ContainerAllocator& _alloc)
    : outputs(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _outputs_type;
  _outputs_type outputs;




  typedef boost::shared_ptr< ::pwm_control::PWMValues_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pwm_control::PWMValues_<ContainerAllocator> const> ConstPtr;

}; // struct PWMValues_

typedef ::pwm_control::PWMValues_<std::allocator<void> > PWMValues;

typedef boost::shared_ptr< ::pwm_control::PWMValues > PWMValuesPtr;
typedef boost::shared_ptr< ::pwm_control::PWMValues const> PWMValuesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pwm_control::PWMValues_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pwm_control::PWMValues_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pwm_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'pwm_control': ['/home/erle/ROS-Robot/src/pwm_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pwm_control::PWMValues_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pwm_control::PWMValues_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pwm_control::PWMValues_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pwm_control::PWMValues_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pwm_control::PWMValues_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pwm_control::PWMValues_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pwm_control::PWMValues_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2710679c2f2cf91e01db75d8355eaf6d";
  }

  static const char* value(const ::pwm_control::PWMValues_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2710679c2f2cf91eULL;
  static const uint64_t static_value2 = 0x01db75d8355eaf6dULL;
};

template<class ContainerAllocator>
struct DataType< ::pwm_control::PWMValues_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pwm_control/PWMValues";
  }

  static const char* value(const ::pwm_control::PWMValues_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pwm_control::PWMValues_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] outputs\n\
";
  }

  static const char* value(const ::pwm_control::PWMValues_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pwm_control::PWMValues_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.outputs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct PWMValues_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pwm_control::PWMValues_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pwm_control::PWMValues_<ContainerAllocator>& v)
  {
    s << indent << "outputs[]" << std::endl;
    for (size_t i = 0; i < v.outputs.size(); ++i)
    {
      s << indent << "  outputs[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.outputs[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PWM_CONTROL_MESSAGE_PWMVALUES_H
